spring:
  application:
    name: esc-server
  datasource:
    url: jdbc:mariadb://localhost:3306/esc
    username: YOUR-DB-USERNAME
    password: YOUR-DB-PASSWORD
    driver-class-name: org.mariadb.jdbc.Driver
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
esc:
  jwt-secret: RANDOM-SECRET
  upload-path: ./upload
  backup-path: ./backup
